sonata_seo:
    encoding:         UTF-8
    page:
        title:           'Florence assistante Maternelle'
        # title_prefix:  'Prefix |'
        # title_suffix:  '| Suffix'
        default:          sonata.seo.page.default
        metas:
            name:
                keywords:             assistante maternelle, florence Houry, Enfant, nourrice
                description:          Florence, l'assistante maternelle qu'il vous faut !
                robots:               index, follow

            property:
                # Facebook application settings
                #'fb:app_id':          XXXXXX
                #'fb:admins':          admin1, admin2

                # Open Graph information
                # see http://developers.facebook.com/docs/opengraphprotocol/#types or http://ogp.me/
                'og:site_name':       Florence assistante Maternelle
                'og:description':      Florence, l'assistante maternelle qu'il vous faut !
                'og:title':    Florence assistante Maternelle
                'og:url':  https://florence-houry.deviteasy.fr/
                'og:type': website
                'og:image': https://florence-houry.deviteasy.fr/build/images/header-bg.8171e118.webp
                
            http-equiv:
                'Content-Type':         text/html; charset=utf-8
                #'X-Ua-Compatible':      IE=EmulateIE7

            charset:
                UTF-8:    ''

        head:
            'xmlns':              http://www.w3.org/1999/xhtml
            'xmlns:og':           http://opengraphprotocol.org/schema/
            #'xmlns:fb':           "http://www.facebook.com/2008/fbml"